# Generated by Django 4.2.16 on 2024-12-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0002_driver_passenger_user_is_driver_user_is_passenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers_photos/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_licenses/'),
        ),
    ]
