# Generated by Django 4.2.18 on 2025-01-29 09:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing', '0004_alter_ride_dropoff_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
